# Generated by Django 2.2.5 on 2019-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='Medicine Name')),
                ('manufacturer', models.CharField(max_length=128, verbose_name='Medicine Manufacturer')),
                ('supplier', models.CharField(max_length=128, verbose_name='Medicine Supplier')),
                ('stock', models.IntegerField(verbose_name='Medicine Stock')),
                ('purchase_price', models.IntegerField(verbose_name='Medicine Purchase Price')),
                ('retail_price', models.IntegerField(verbose_name='Medicine Retail Price')),
                ('medicine_type', models.CharField(choices=[('O', 'Oral'), ('I', 'IV')], max_length=1)),
            ],
        ),
    ]
